import { serve } from "https://deno.land/std@0.224.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

function jsonResponse(body: Record<string, unknown>, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      ...corsHeaders,
      "Content-Type": "application/json",
    },
  });
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (req.method !== "POST") {
    return jsonResponse({ error: "Method not allowed" }, 405);
  }

  try {
    const { sessionData } = await req.json();

    if (!sessionData) {
      return jsonResponse({ error: "Missing sessionData" }, 400);
    }

    const apiKey = Deno.env.get("GEMINI_API_KEY");

    if (!apiKey) {
      return jsonResponse({ error: "Missing GEMINI_API_KEY" }, 500);
    }

    const prompt = `
You are the AI assistant of Class Connect, a classroom participation system.

Generate a professional, printable AI session summary report.

Rules:
- Do not invent names, points, times, events, attendance, or class details.
- If a value is missing, write "N/A" or "Not recorded".
- Write in a clear, formal teacher-report style.
- Keep paragraphs concise and printable.

============================================================
CLASS CONNECT - AI SESSION SUMMARY REPORT
============================================================

HEADER
Class Connect
"LEVEL UP YOUR CLASS"

Institution: Gordon College - College of Computer Studies
Instructor: [Teacher Name]
Subject: [Subject Name]
Class Code: [Class Code]
Program/Year/Block: [Program/Year/Block]

------------------------------------------------------------
SESSION DETAILS
------------------------------------------------------------
Session Title: [Session Title or N/A]
Date: [Date]
Time Started: [Time Started]
Time Ended: [Time Ended]
Duration: [Duration]
Total Students Present: [#]
Late Entries After 15 Minutes: [#]

------------------------------------------------------------
OVERALL PARTICIPATION SUMMARY
------------------------------------------------------------
[Write one professional paragraph summarizing overall engagement.]

------------------------------------------------------------
PARTICIPATION BREAKDOWN
------------------------------------------------------------
Active Participants:
- [Student Name] - Times Called: [#] - Points: [#]

Low / No Participation:
- [Student Name] - Status: [Low participation / No recorded participation]

------------------------------------------------------------
VOLUNTEER ACTIVITY
------------------------------------------------------------
Volunteer Queue / Activity:
- [Student Name or Not recorded]

AI Insight:
[Write 1-2 professional sentences.]

------------------------------------------------------------
POINT DISTRIBUTION
------------------------------------------------------------
Total Points Given: [#]
Average Points per Student: [#]
Highest Points Earned: [Student Name - # points]

------------------------------------------------------------
ENGAGEMENT ANALYSIS
------------------------------------------------------------
[Write one short paragraph.]

------------------------------------------------------------
TEACHER RECOMMENDATIONS FOR NEXT SESSION
------------------------------------------------------------
- [Recommendation 1]
- [Recommendation 2]
- [Recommendation 3]

------------------------------------------------------------
SYSTEM NOTES
------------------------------------------------------------
- Weighted Random Selection was used to support fair participation.
- Volunteer queue activity was recorded when available.
- Participation tracking is based on real-time session records and teacher input.

============================================================
FOOTER
Generated by Class Connect AI Assistant
Report prepared for teacher review and printable session documentation.
============================================================

SESSION DATA:
${JSON.stringify(sessionData, null, 2)}
`;

    const geminiRes = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              role: "user",
              parts: [{ text: prompt }],
            },
          ],
          generationConfig: {
            temperature: 0.3,
            topP: 0.8,
            maxOutputTokens: 1600,
          },
        }),
      }
    );

    const data = await geminiRes.json();

    console.log("Gemini Status:", geminiRes.status);
    console.log("Gemini Response:", JSON.stringify(data));

    if (!geminiRes.ok) {
      return jsonResponse(
        {
          error: "Gemini request failed",
          details: data.error?.message || "No details returned by Gemini.",
        },
        geminiRes.status
      );
    }

    const summary =
      data.candidates?.[0]?.content?.parts?.[0]?.text?.trim() ||
      "No summary generated.";

    return jsonResponse({ summary });
  } catch (error) {
    console.error("Function Error:", error);
    return jsonResponse({ error: String(error) }, 500);
  }
});
